// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoshkarOla.API.Data;

#nullable disable

namespace YoshkarOla.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YoshkarOla.API.Models.Attraction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Address").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<string>("ImageUrl").IsRequired().HasColumnType("text");
                b.Property<bool>("IsFree").HasColumnType("boolean");
                b.Property<double>("Latitude").HasColumnType("double precision");
                b.Property<double>("Longitude").HasColumnType("double precision");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<double>("Rating").HasColumnType("double precision");
                b.Property<string>("ShortDescription").IsRequired().HasColumnType("text");
                b.Property<string>("WorkingHours").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Category");
                b.ToTable("Attractions");
            });

            modelBuilder.Entity("YoshkarOla.API.Models.Event", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Address").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<DateTime?>("EndDate").HasColumnType("timestamp with time zone");
                b.Property<string>("ImageUrl").IsRequired().HasColumnType("text");
                b.Property<bool>("IsFree").HasColumnType("boolean");
                b.Property<string>("Location").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<int?>("Price").HasColumnType("integer");
                b.Property<string>("ShortDescription").IsRequired().HasColumnType("text");
                b.Property<DateTime>("StartDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.HasKey("Id");
                b.HasIndex("StartDate");
                b.ToTable("Events");
            });

            modelBuilder.Entity("YoshkarOla.API.Models.Hotel", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Address").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<string[]>("Amenities").IsRequired().HasColumnType("text[]");
                b.Property<string>("CheckIn").IsRequired().HasColumnType("text");
                b.Property<string>("CheckOut").IsRequired().HasColumnType("text");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<string>("DescriptionAttractions").IsRequired().HasColumnType("text");
                b.Property<string>("DescriptionFood").IsRequired().HasColumnType("text");
                b.Property<string>("DescriptionInfrastructure").IsRequired().HasColumnType("text");
                b.Property<string>("DescriptionLocation").IsRequired().HasColumnType("text");
                b.Property<string>("DescriptionRooms").IsRequired().HasColumnType("text");
                b.Property<string>("DescriptionService").IsRequired().HasColumnType("text");
                b.Property<bool>("HasParking").HasColumnType("boolean");
                b.Property<bool>("HasPool").HasColumnType("boolean");
                b.Property<bool>("HasRestaurant").HasColumnType("boolean");
                b.Property<bool>("HasWifi").HasColumnType("boolean");
                b.Property<string>("ImageUrl").IsRequired().HasColumnType("text");
                b.Property<string[]>("Images").IsRequired().HasColumnType("text[]");
                b.Property<double>("Latitude").HasColumnType("double precision");
                b.Property<double>("Longitude").HasColumnType("double precision");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Phone").IsRequired().HasColumnType("text");
                b.Property<int>("PriceFrom").HasColumnType("integer");
                b.Property<double>("Rating").HasColumnType("double precision");
                b.Property<double>("RatingCleanliness").HasColumnType("double precision");
                b.Property<double>("RatingFood").HasColumnType("double precision");
                b.Property<double>("RatingHygiene").HasColumnType("double precision");
                b.Property<double>("RatingLocation").HasColumnType("double precision");
                b.Property<double>("RatingPrice").HasColumnType("double precision");
                b.Property<double>("RatingRoom").HasColumnType("double precision");
                b.Property<double>("RatingService").HasColumnType("double precision");
                b.Property<double>("RatingWifi").HasColumnType("double precision");
                b.Property<int>("ReviewCount").HasColumnType("integer");
                b.Property<string>("ShortDescription").IsRequired().HasColumnType("text");
                b.Property<int>("Stars").HasColumnType("integer");
                b.Property<string>("Website").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Stars");
                b.ToTable("Hotels");
            });

            modelBuilder.Entity("YoshkarOla.API.Models.Restaurant", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Address").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                b.Property<string>("Cuisine").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Description").IsRequired().HasColumnType("text");
                b.Property<bool>("HasDelivery").HasColumnType("boolean");
                b.Property<string>("ImageUrl").IsRequired().HasColumnType("text");
                b.Property<double>("Latitude").HasColumnType("double precision");
                b.Property<double>("Longitude").HasColumnType("double precision");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Phone").IsRequired().HasColumnType("text");
                b.Property<string>("PriceRange").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<double>("Rating").HasColumnType("double precision");
                b.Property<string>("ShortDescription").IsRequired().HasColumnType("text");
                b.Property<string>("WorkingHours").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Cuisine");
                b.ToTable("Restaurants");
            });
#pragma warning restore 612, 618
        }
    }
}
